import type { Metadata, Viewport } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import AppShell from "@/components/AppShell";
import SocketInit from "@/components/SocketInit";
import Progress from "@/components/Progress";
import AppReady from "@/components/AppReady";

const nunito = Nunito({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#f8f5f2",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased`}>
        <AppReady>
          <AppShell>
            {children}

            <Toaster position="bottom-center" />
            <SocketInit />
            <Progress />
          </AppShell>
        </AppReady>
      </body>
    </html>
  );
}
